"""Second migration

Revision ID: 064023d75f07
Revises: 2e5f93df05ba
Create Date: 2024-04-19 02:29:34.621046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064023d75f07'
down_revision = '2e5f93df05ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.drop_column('profile_type')

    # ### end Alembic commands ###
