"""Second migration

Revision ID: 9f05dff20357
Revises: f0a8f15e13b0
Create Date: 2024-04-19 02:27:45.033853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f05dff20357'
down_revision = 'f0a8f15e13b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_plan', schema=None) as batch_op:
        batch_op.drop_column('profile_type')

    # ### end Alembic commands ###
