"""Four Migration

Revision ID: f3cd8d92c851
Revises: b3cea3e210e5
Create Date: 2024-05-16 08:20:11.430892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cd8d92c851'
down_revision = 'b3cea3e210e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strava_activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('athlete_id',
               existing_type=sa.Integer(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strava_activity', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('athlete_id',
               existing_type=sa.BigInteger(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###
