steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA', '.']
    dir: 'Backend/core_functionalities/event_management_commands'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA']

  # Create a network
  - name: 'gcr.io/cloud-builders/docker'
    args: ['network', 'create', 'em-net']

  # Start PostgreSQL container on the network
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--name', 'postgres-em-commands', '--network', 'em-net', '-e', 'POSTGRES_DB=db_event_management_commands', '-e', 'POSTGRES_USER=postgres', '-e', 'POSTGRES_PASSWORD=emCommands', '-d', 'postgres:13']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        while ! docker exec postgres-em-commands pg_isready -U postgres -d db_event_management_commands; do sleep 1; done

  # Run tests inside the Docker container
 # Run tests inside the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $$SECRET_VALUE > /workspace/creds.json
        docker run --rm --network em-net \
        -e GOOGLE_APPLICATION_CREDENTIALS=/creds/creds.json \
        -v /workspace/creds.json:/creds/creds.json \
        -v /workspace/Backend/core_functionalities/event_management_commands:/usr/src \
        -w /usr/src \ 
        -e DATABASE_URL=postgresql://postgres:emCommands@postgres-em-commands:5432/db_event_management_commands \
        gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA \
        bash -c "python -m coverage run --source=. -m unittest discover -s tests -v && \
                 python -m coverage xml -o coverage.xml && \
                 python -m coverage report; \
                 ls -al /usr/src"

    # Set the environment variable from the secret
    secretEnv: ['SECRET_VALUE']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing /usr/src directory contents to verify presence of coverage.xml..."
        ls -al /usr/src
        echo "Running SonarQube Scanner..."
        docker run --rm \
          -e SONAR_TOKEN=$$SONAR_TOKEN \
          -e SONAR_HOST_URL="https://sonarcloud.io" \
          -e SONAR_PROJECT_KEY=$$SONAR_PROJECT_KEY \
          -e SONAR_ORG=$$SONAR_ORG \
          -v $(pwd)/Backend/core_functionalities/event_management_commands:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=$$SONAR_PROJECT_KEY \
          -Dsonar.organization=$$SONAR_ORG \
          -Dsonar.sources=. \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.python.coverage.reportPaths=/usr/src/coverage.xml \
          -Dsonar.verbose=true
    secretEnv: ['SONAR_TOKEN', 'SONAR_PROJECT_KEY', 'SONAR_ORG']

  # Stop the PostgreSQL container
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['stop', 'postgres-em-commands']

  # Remove the PostgreSQL container
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['rm', 'postgres-em-commands']

  # Remove the network
  #- name: 'gcr.io/cloud-builders/docker'
  #  args: ['network', 'rm', 'em-net']

# Define the secret available to this build
availableSecrets:
  secretManager:
    - versionName: 'projects/miso-proyecto-de-grado-g09/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/latest'
      env: 'SECRET_VALUE'
    - versionName: projects/$PROJECT_ID/secrets/SONAR_TOKEN/versions/latest
      env: 'SONAR_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/SONAR_PROJECT_KEY/versions/latest
      env: 'SONAR_PROJECT_KEY'
    - versionName: projects/$PROJECT_ID/secrets/SONAR_ORG/versions/latest
      env: 'SONAR_ORG'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  substitution_option: ALLOW_LOOSE
