steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', 'gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA', '.']
    dir: 'Backend/core_functionalities/event_management_commands'

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA']

  # Run tests inside the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Export the secret to a file
        echo $$SECRET_VALUE > /workspace/creds.json
        
        # Run the container with the credential file mounted and environment variable set
        docker run --rm -e GOOGLE_APPLICATION_CREDENTIALS=/creds/creds.json -v /workspace/creds.json:/creds/creds.json \
        -e FLASK_ENV=testing gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA python -m coverage run --source=. -m unittest discover -s tests && \
        docker run --rm -e GOOGLE_APPLICATION_CREDENTIALS=/creds/creds.json -v /workspace/creds.json:/creds/creds.json \
        gcr.io/$PROJECT_ID/event-management-commands:$SHORT_SHA python -m coverage xml -o coverage.xml

    # Set the environment variable from the secret
    secretEnv: ['SECRET_VALUE']

# Define the secret available to this build
availableSecrets:
  secretManager:
    - versionName: 'projects/miso-proyecto-de-grado-g09/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/latest'
      env: 'SECRET_VALUE'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  substitution_option: ALLOW_LOOSE
