steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Attempting to access secret..."
        # Use the secret directly; make sure there's no confusion with Cloud Build substitutions
        echo "Secret content: $$SECRET_VALUE"
    # Correct usage of secretEnv to map the secret to an environment variable
    secretEnv: ['SECRET_VALUE']

# Define the secret available to this build
availableSecrets:
  secretManager:
    - versionName: 'projects/miso-proyecto-de-grado-g09/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/latest'
      env: 'SECRET_VALUE'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  substitution_option: ALLOW_LOOSE
