# Define la etiqueta que activa el trigger.
# trigger:
#   tags:
#     - release-user 

steps:
# Paso 1: Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/miso-proyecto-de-grado-g09/docker-images-g9/user_management:latest', './user_management']

# Paso 2: Subir la imagen a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/miso-proyecto-de-grado-g09/docker-images-g9/user_management:latest']

# Paso 3: Aplicar el archivo de configuración de Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/k8s-services-ms-user.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-proyecto-final'
  
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  substitution_option: ALLOW_LOOSE