steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Attempting to access secret..."
        # Use the environment variable directly without the dollar sign in the echo command.
        # This helps in avoiding confusion with substitutions.
        echo "Secret content: ${SECRET_VALUE}"
        if [ -z "${SECRET_VALUE}" ]; then
          echo "No secret content available, access error."
        fi
    secretEnv: ['SECRET_VALUE']

availableSecrets:
  secretManager:
    - versionName: 'projects/miso-proyecto-de-grado-g09/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/latest'
      env: 'SECRET_VALUE'

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  substitution_option: ALLOW_LOOSE
