version: '3'

services:
  
  db_event_management_commands:
    image: postgres:13
    container_name: db_em_commands
    environment:
      POSTGRES_DB: db_event_management_commands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emCommands
    networks:
      - em_net

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db_event_management_commands"]
        interval: 5s
        timeout: 10s
        retries: 5

  event_management_commands:
    build:
      context: ./core_functionalities/event_management_commands
    container_name: event_management_commands_container
    ports:
      - "3001:3001"
    depends_on:
      - db_event_management_commands
    environment:
      DATABASE_URL: postgresql://postgres:emCommands@db_event_management_commands:5432/db_event_management_commands
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_event_management_queries:
    image: postgres:13
    container_name: db_em_queries
    environment:
      POSTGRES_DB: db_event_management_queries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emQueries
    networks:
      - em_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_event_management_queries"]
      interval: 5s
      timeout: 10s
      retries: 5

  event_management_queries:
    build:
      context: ./core_functionalities/event_management_queries
    container_name: event_management_queries_container
    ports:
      - "3002:3002"
    depends_on:
      db_event_management_queries:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:emQueries@db_event_management_queries:5432/db_event_management_queries
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_training_management_commands:
    image: postgres:13
    container_name: db_tm_commands
    environment:
      POSTGRES_DB: db_training_management_commands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tmCommands
    networks:
      - em_net

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db_training_management_commands"]
        interval: 5s
        timeout: 10s
        retries: 5

  training_management_commands:
    build:
      context: ./core_functionalities/training_management_commands
    container_name: training_management_commands_container
    ports:
      - "3004:3004"
    depends_on:
      - db_training_management_commands
    environment:
      DATABASE_URL: postgresql://postgres:tmCommands@db_training_management_commands:5432/db_training_management_commands
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_training_management_queries:
    image: postgres:13
    container_name: db_tm_queries
    environment:
      POSTGRES_DB: db_training_management_queries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tmQueries
    networks:
      - em_net

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db_training_management_queries"]
        interval: 5s
        timeout: 10s
        retries: 5

  training_management_queries:
    build:
      context: ./core_functionalities/training_management_queries
    container_name: training_management_queries_container
    ports:
      - "3003:3003"
    depends_on:
      db_training_management_queries:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:tmQueries@db_training_management_queries:5432/db_training_management_queries
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_service_management:
      image: postgres:13
      container_name: db_service_management
      environment:
        POSTGRES_DB: db_service_management
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: smServices
      networks:
        - em_net

      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d db_service_management"]
          interval: 5s
          timeout: 10s
          retries: 5

  service_management:
    build:
      context: ./core_functionalities/services_management
    container_name: service_management_container
    ports:
      - "3005:3005"
    depends_on:
      db_service_management:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:smServices@db_service_management:5432/db_service_management
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_user_management_commands:
    image: postgres:13
    container_name: db_um_commands
    environment:
      POSTGRES_DB: db_user_management_commands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: umCommands
    networks:
      - em_net

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db_user_management_commands"]
        interval: 5s
        timeout: 10s
        retries: 5

  user_management_commands:
    build:
      context: ./core_functionalities/user_management_commands
    container_name: user_management_commands_container
    ports:
      - "3006:3006"
    depends_on:
      - db_user_management_commands
    environment:
      DATABASE_URL: postgresql://postgres:umCommands@db_user_management_commands:5432/db_user_management_commands
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

  db_user_management_queries:
    image: postgres:13
    container_name: db_um_queries
    environment:
      POSTGRES_DB: db_user_management_queries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: umQueries
    networks:
      - em_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_user_management_queries"]
      interval: 5s
      timeout: 10s
      retries: 5

  user_management_queries:
    build:
      context: ./core_functionalities/user_management_queries
    container_name: user_management_queries_container
    ports:
      - "3007:3007"
    depends_on:
      db_user_management_queries:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:umQueries@db_user_management_queries:5432/db_user_management_queries
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/service-account.json
    volumes:
      - ../../../service-account.json:/secrets/service-account.json
    networks:
      - em_net

networks:
  # app_net:
  tmq_net:
  em_net:
    driver: bridge