apiVersion: batch/v1
kind: Job
metadata:
  name: service-management-migration
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: gcr.io/miso-proyecto-de-grado-g09/service-management:latest
        command: ["flask", "db", "upgrade"]
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:smServices@db-service-management:5432/db_service_management
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 30
