apiVersion: batch/v1
kind: Job
metadata:
  name: training-management-queries-migration
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: gcr.io/miso-proyecto-de-grado-g09/training-management-queries:latest
        command: ["flask", "db", "upgrade"]
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:tmQueries@db-training-management-queries:5432/db_training_management_queries
      restartPolicy: OnFailure
