"""Initial migration

Revision ID: 09c032f5be2e
Revises: 
Create Date: 2024-04-30 22:14:40.627577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c032f5be2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=False),
    sa.Column('city_of_living', sa.String(length=100), nullable=True),
    sa.Column('country_of_living', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('city_of_birth', sa.String(length=100), nullable=True),
    sa.Column('country_of_birth', sa.String(length=100), nullable=True),
    sa.Column('sports', sa.String(length=200), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('blood_pressure', sa.String(length=50), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('training_frequency', sa.String(length=50), nullable=True),
    sa.Column('sports_practiced', sa.String(length=200), nullable=True),
    sa.Column('average_session_duration', sa.Integer(), nullable=True),
    sa.Column('recovery_time', sa.Integer(), nullable=True),
    sa.Column('training_pace', sa.String(length=50), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('daily_calories', sa.Integer(), nullable=True),
    sa.Column('daily_protein', sa.Integer(), nullable=True),
    sa.Column('daily_liquid', sa.Integer(), nullable=True),
    sa.Column('daily_carbs', sa.Integer(), nullable=True),
    sa.Column('meal_frequency', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
