"""Second migration

Revision ID: 977e81a9ec2d
Revises: 09c032f5be2e
Create Date: 2024-05-06 17:50:07.943685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '977e81a9ec2d'
down_revision = '09c032f5be2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('current_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_active_session', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active_session')
        batch_op.drop_column('current_token')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
