"""Second migration plan type

Revision ID: 696f7797c8e5
Revises: b98c230c8665
Create Date: 2024-04-22 14:20:07.591848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696f7797c8e5'
down_revision = 'b98c230c8665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan_type')

    # ### end Alembic commands ###
