apiVersion: v1
kind: Service
metadata:
  name: db-training-management-commands
spec:
  type: ClusterIP  # Default type, suitable for internal communication
  ports:
    - port: 5432  # PostgreSQL default port
      targetPort: 5432
  selector:
    app: db-training-management-commands  # This should match the labels of the database pods
