apiVersion: v1
kind: Service
metadata:
  name: db-user-management-queries
spec:
  type: ClusterIP  # Default type, suitable for internal communication
  ports:
    - port: 5432  # PostgreSQL default port
      targetPort: 5432
  selector:
    app: db-user-management-queries 
