apiVersion: v1
kind: Service
metadata:
  name: event-management-commands
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  selector:
    app: event-management-commands  # This should match labels of the pods
