apiVersion: v1
kind: Service
metadata:
  name: event-management-queries
spec:
  ports:
    - name: http
      port: 3002
      targetPort: 3002
  selector:
    app: event-management-queries  # This should match labels of the pods
