apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-commands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-management-commands
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: event-management-commands
    spec:
      containers:
      - name: event-management-commands-container
        image: gcr.io/miso-proyecto-de-grado-g09/event-management-commands:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:emCommands@db-event-management-commands:5432/db_event_management_commands
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/service-account.json
        volumeMounts:
        - mountPath: /secrets
          name: sa-key-volume
          readOnly: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: sa-key-volume
        secret:
          secretName: sa-key
      restartPolicy: Always