apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-management-commands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-management-commands
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: training-management-commands
    spec:
      containers:
      - name: training-management-commands-container
        image: gcr.io/miso-proyecto-de-grado-g09/training-management-commands:latest
        ports:
        - containerPort: 3004
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:tmCommands@db-training-management-commands:5432/db_training_management_commands
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/service-account.json
        volumeMounts:
        - mountPath: /secrets
          name: sa-key-volume
          readOnly: true
      volumes:
      - name: sa-key-volume
        secret:
          secretName: sa-key
      restartPolicy: Always
