apiVersion: v1
kind: Service
metadata:
  name: training-management-queries
spec:
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  selector:
    app: training-management-queries  # Adjusted to match the labels of the pods appropriately
