apiVersion: v1
kind: Service
metadata:
  name: training-management-commands
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3004
      targetPort: 3004
  selector:
    app: training-management-commands  # Adjusted to match the labels of the pods appropriately
